data:
  prob_train: 0.8
  
  training_size: 150

  #delimiter: _
  maxvalues: [255,1023,1023]
  
  root_folder: data
  suffixes: null # Para cimgs todos los canales van en un solo archivo .cimg
  channel_list: null
  use_segmentation_masks : true # Use annotated masks

  train:
  - -  train_list.txt
    - 20240219_190526_Img_20240219_NaranjaRottEncoder/jsons
    - 20240219_190526_Img_20240219_NaranjaRottEncoder/images
  - -  train_list.txt
    - 20240220_142555_Img_20240220_goods/jsons
    - 20240220_142555_Img_20240220_goods/images
  - -  train_list.txt
    - 20240312_210918_prod/jsons
    - 20240312_210918_prod/images
  - -  train_list.txt
    - 20240312_210929_prod/jsons
    - 20240312_210929_prod/images
  - -  train_list.txt
    - 20240321_162918_Img_20240321_162913/jsons
    - 20240321_162918_Img_20240321_162913/images
  - -  train_list.txt
    - 20240321_172502_defectos_rotando/jsons
    - 20240321_172502_defectos_rotando/images
  - - train_list.txt
    - 20240805/jsons
    - 20240805/images
  - -  train_list.txt
    - 20240312_211001_prod/20240805/jsons
    - 20240312_211001_prod/20240805/images
  - -  train_list.txt
    - 20240321_163007_Img_20240321_162913/20240805/jsons
    - 20240321_163007_Img_20240321_162913/20240805/images


  

  val:
  - - val_list.txt
    - lote1/jsons
    - lote1/images
  - - val_list.txt
    - lote2/20230419_100534_BuenoEncoder/jsons  
    - lote2/20230419_100534_BuenoEncoder/imags
  - - val_list.txt
    - lote2/20230419_112500_BuenoEncoder/jsons  
    - lote2/20230419_112500_BuenoEncoder/imags
  - - val_list.txt
    - lote2/20230419_113002_LagrimaEncoder/jsons  
    - lote2/20230419_113002_LagrimaEncoder/imags
  - - val_list.txt
    - lote2/20230419_114356_CicatrizDefSupEncoder/jsons  
    - lote2/20230419_114356_CicatrizDefSupEncoder/imags
  - - val_list.txt
    - lote2/20230419_115102_HojaRaboConDeformeEncoder/jsons  
    - lote2/20230419_115102_HojaRaboConDeformeEncoder/imags
  - - val_list.txt
    - lote2/20230419_115631_DestrioRotaEncoder/jsons  
    - lote2/20230419_115631_DestrioRotaEncoder/imags
  - - val_list.txt
    - lote2/20230419_120236_DeformesDoblesEncoder/jsons  
    - lote2/20230419_120236_DeformesDoblesEncoder/imags
  - - val_list.txt
    - lote2/20230419_122046ArrugadoEncoder/jsons  
    - lote2/20230419_122046ArrugadoEncoder/imags
  - - val_list.txt
    - lote2/20230419_121536_BlandoEncoder/jsons  
    - lote2/20230419_121536_BlandoEncoder/imags
  - - val_list.txt
    - lote2/20230419_122528_VerdeRojoEncoder/jsons  
    - lote2/20230419_122528_VerdeRojoEncoder/imags           

model:
  defect_types:
  - Blandos
  - Cicatrices
  - defectos_severos
  - Deformes
  - Deshidratado
  - Flor_seca
  - Lagrima
  - Rabos
  - Rojos
  - Verdes
  num_channels_input: 4
  model_version: 50

train:  
  batch_size: 30
  epochs: 40
  in_memory: true
  initial_model: null
  label_smoothing: 0.1
  learning_rate: 0.01
  optimizer: sgd
  num_workers: -1
  output:
    model_file: arandanos2.pkl
    path: out_models
  p_dropout: 0.5 
  unfreeze_epoch: 6
  warmup: 3
  weights_decay: 0.001
  logname: orange_mil_segmentation
  wandb_project: DVC_segmentation  

  augmentation:
    random_rotation: 30
    brightness: 
    - 0.8
    - 1.4
    contrast:
    - 0.8
    - 1.55
    hue: 0.01
    saturation: 0.15
    blur:
    - 0.1
    - 1.5
    affine:
      scale:
      - 0.7
      - 1.1
      shear: 15
      translate: 
      - 0.15
      - 0.15
      degrees: 30

evaluate:
  model_dir: out_models
  model_file: arandanos2.pkl
  
  report_dir: out_evaluate
  train_predictions: train_scores.json
  val_predictions: val_scores.json
  aucs: aucs.json


predict:
  model_dir: out_models
  model_file: arandanos2.pkl
  patron: "*.cimg"
  
  report_dir: out_predict
    