data:
  prob_train: 0.8
  
  training_size: 
  - 150
  - 150
  crop_size: null

  delimiter: _
  maxvalues: [255,1023,1023]
  
  root_folder: data
  suffixes: 
  - _RGB.png
  - _NIR.png
  - _UV.png
  channel_list: null
  use_segmentation_masks : true # Use annotated masks

  train:
  - - train_list.txt
    - 20240219_190526_Img_20240219_NaranjaRottEncoder/jsons
    - 20240219_190526_Img_20240219_NaranjaRottEncoder/images
  - - train_list.txt
    - 20240220_142555_Img_20240220_goods/jsons
    - 20240220_142555_Img_20240220_goods/images
  - - train_list.txt
    - 20240312_210918_prod/jsons
    - 20240312_210918_prod/images
  - - train_list.txt
    - 20240312_210929_prod/jsons
    - 20240312_210929_prod/images
  - - train_list.txt
    - 20240321_162918_Img_20240321_162913/jsons
    - 20240321_162918_Img_20240321_162913/images
  - - train_list.txt
    - 20240321_172502_defectos_rotando/jsons
    - 20240321_172502_defectos_rotando/images
  - - train_list.txt
    - 20240805/jsons
    - 20240805/images
  - - train_list.txt
    - 20240805b/jsons
    - 20240805b/images
  - - train_list.txt
    - 20240805c/jsons
    - 20240805c/images


  
  val:
  - - val_list.txt
    - 20240219_190526_Img_20240219_NaranjaRottEncoder/jsons
    - 20240219_190526_Img_20240219_NaranjaRottEncoder/images
  - - val_list.txt
    - 20240220_142555_Img_20240220_goods/jsons
    - 20240220_142555_Img_20240220_goods/images
  - - val_list.txt
    - 20240312_210918_prod/jsons
    - 20240312_210918_prod/images
  - - val_list.txt
    - 20240312_210929_prod/jsons
    - 20240312_210929_prod/images
  - - val_list.txt
    - 20240321_162918_Img_20240321_162913/jsons
    - 20240321_162918_Img_20240321_162913/images
  - - val_list.txt
    - 20240321_172502_defectos_rotando/jsons
    - 20240321_172502_defectos_rotando/images
  - - val_list.txt
    - 20240805/jsons
    - 20240805/images
  - - val_list.txt
    - 20240805b/jsons
    - 20240805b/images
  - - val_list.txt
    - 20240805c/jsons
    - 20240805c/images

model:
  defect_types:
  - "Pedunculo"
  - "Contraped"

  num_channels_input: 5
  model_version: 50 # Options: 50 , MobileNet

train:  
  initial_model: null
  batch_size: 30
  in_memory: true
  num_workers: 10    

#Learning
  epochs: 2 
  unfreeze_epoch: 6
  warmup: 2
  learning_rate: 0.003  
  optimizer: adam
  gamma_param: 0.1

# Regularization
  label_smoothing: 0.1
  p_dropout: 0.5 
  weights_decay: 0.001

  output:
    model_file: arandanos2.pkl
    path: out_models

# MIL
  min_defect_area: 50
  constrain_weight: 5.0
  min_negative_fraction: 0.95
  bottom_constrain_weight: 1.0
  binmask_weight: 30.0 
  class_weights: 
  - 1.0
  - 1.0


  logname: orange_mil_segmentation
  wandb_project: DVC_segmentation  

  augmentation:
    random_rotation: 30
    brightness: 
    - 0.8
    - 1.4
    contrast:
    - 0.8
    - 1.55
    hue: 0.01
    saturation: 0.15
    blur:
    - 0.1
    - 1.5
    affine:
      scale:
      - 0.7
      - 1.1
      shear: 15
      translate: 
      - 0.15
      - 0.15
      degrees: 30

evaluate:
  model_dir: out_models
  model_file: arandanos2.pkl
  
  report_dir: out_evaluate
  train_predictions: train_scores.json
  val_predictions: val_scores.json
  aucs: aucs.json


predict:
  model_dir: out_models
  model_file: arandanos2.pkl
  patron: "*.cimg"
  
  report_dir: out_predict
    